FROM node:lts-alpine
LABEL maintainer="Evine Deng <evinedeng@foxmail.com>"
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.bfsu.edu.cn/g' /etc/apk/repositories && \
    apk update -f && \
    apk --no-cache add -f openssl coreutils git wget curl nano tzdata perl bash && \
    rm -rf /var/cache/apk/*
ENV HOME=/root LANGUAGE=en_US.UTF-8 LANG=en_US.UTF-8 LC_ALL=C SHELL=/bin/bash PS1="\u@\h:\w \$ "
COPY Docker/entrypoint.sh /entrypoint.sh
COPY first_run.sh /first_run.sh 
RUN chmod 777 /entrypoint.sh && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone
WORKDIR /root
VOLUME /root
ENTRYPOINT /entrypoint.sh
